SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Radius of the player's ship
PLAYER_RADIUS = 20

# Width fo the lines that draw the player's ship
LINE_WIDTH = 2

# Turn speed
PLAYER_TURN_SPEED = 300

# player speed
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 30
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 10
PLAYER_SHOOT_SPEED = 500
